name: Deploy to Plesk

on:
  push:
    branches:
      - master  # Déploie quand on push sur "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Construire le projet
        run: npm run build

      - name: Synchroniser avec le serveur Plesk
        run: |
          rsync -avz --delete-after .next public package.json lucid-roentgen.217-154-14-66.plesk.page:/var/www/vhosts/lucid-roentgen.217-154-14-66.plesk.page/httpdocs
